server:
  port: 8080

spring:
  profiles:
    - docker
  r2dbc:
    url: r2dbc:pool:postgresql://timescaledb:5432/postgres
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://timescaledb:5432/postgres
    user: postgres
    password: password
  cloud:
    stream:
      kafka.binder:
        brokers:
          - kafka_0:29092
          - kafka_1:29093