server:
  port: 8092
  context-path: /consumer-api

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/iot_db
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/iot_db
    user: postgres
    password: password
  profiles: local
  application.name: consumer-api
  cloud:
    stream:
      bindings:
        input:
          binder: kafka
          destination: iot-data
          group: consumer-group-1
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: true
          minPartitionCount: 3
          group: output-group-1
      default-binder: kafka
logging:
  level:
    root: INFO
    br.com.iot: DEBUG
    org.springframework.data.r2dbc: trace
  pattern:
    console: '%highlight(<<%-5level>>) %d{dd-MM-yy HH:mm:ss.SSS} [%thread] %cyan(%c{0}.%M) - %msg%n'